layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  github: thrustsec
  linkedin: thrustsec
  twitter: thrustsec
  youtube: UCmSDfLbq55QogRDV6FxO2jQ

#topics:
#  - name: 
#    web_url: 
#    image_url: 
